### ISSUE TITLE
Метод авторизации /auth возвращает 201

### ISSUE THREAD

**Issue by jemunjho** [NKBelousov/expense-tracker-backend#1]
1) Метод авторизации /auth возвращает 201 код, вместо 200
2) Было бы неплохо переименовать передаваемое поле name в login
3) Было бы неплохо в методе авторизации - просто отдавать access_token; а для получения деталей по пользователю - реализовать отдельный метод

**Comment by NKBelousov** [comment]
@jemunjho 
1 и 2 - сделано
3 - имеешь ввиду отдельный метод, определяющий пользователя по токену в заголовках или вместе с токеном возвращать ID пользователя и GET по ID пользователя?

**Comment by jemunjho** [comment]
3. Я бы предложил второй вариант. Либо - в уже существющем методе - вынести поле token на один уровень с ключем user. Чтобы я мог сохранить отдельно токен и отдельно сущность пользователя.

**Comment by NKBelousov** [comment]
@jemunjho 

* добавил пользователя в ответ `/auth` 
* можно получить своего пользователя методом GET: `/api/user/:id`
