### ISSUE TITLE
Авторизация пользователей: поправить заголовки в ответах

### ISSUE THREAD

**Issue by jemunjho** [NKBelousov/expense-tracker-backend#2]
1) При успешной авторизации - возвращается 201 код; должен быть 200-й.

2) При некорректных доступах - возврвщается ошибка 400; лучше вернуть 403, если пользователь не смог авторизоваться и 404, если пользователь, под доступами которого пытаются авторизоваться - не наиден.

**Comment by NKBelousov** [comment]
@jemunjho 

При успешной авторизации возвращается 201
При неуспешной - 404
При ошибке - 400

Разделять отдельно на 403 и 404 не вижу смысла.
